# Generated by Django 4.2.22 on 2025-06-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[{'Adminstrator', 'admin'}, {'Anfitriao', 'anfitriao'}, {'Convidado', 'guest'}], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveBigIntegerField(default=0)),
                ('profiles', models.ManyToManyField(related_name='menu_items', to='users.profile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
