# Generated by Django 4.2.22 on 2025-06-06 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(choices=[{'Administrador', 'admin'}, {'anfitriao', 'Anfitrião'}, {'guest', 'Convidado'}], max_length=50, unique=True),
        ),
    ]
